"use client";

import { useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { ChevronDown, ChevronRight } from "lucide-react";
import type { MetaCampaignMetric, MetaCampaignReportBootstrap } from "@/lib/data/meta-campaign-report";
import type { SourceClientValue } from "@/lib/data/source-client-types";
import { formatCurrency, formatNumber } from "@/lib/metrics/kpis";
import { Sidebar } from "./sidebar";

export function CampaignAttributionDashboard({ bootstrap, sourceClients }: { bootstrap: MetaCampaignReportBootstrap; sourceClients: SourceClientValue[] }) {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const companyId = bootstrap.selectedCompanyId;

  function setMonth(value: string) {
    const params = new URLSearchParams(searchParams.toString());
    if (value === "ytd") params.delete("month");
    else params.set("month", value);
    const query = params.toString();
    router.push(query ? `${pathname}?${query}` : pathname);
  }
  function setCompany(value: string) {
    const params = new URLSearchParams(searchParams.toString());
    params.set("company", value);
    const query = params.toString();
    setExpandedCampaignId(null);
    router.push(query ? `${pathname}?${query}` : pathname);
  }

  const [expandedCampaignId, setExpandedCampaignId] = useState<string | null>(null);
  const data = bootstrap.datasets[companyId];
  const totals = useMemo(() => data ? totalCampaigns(data.campaigns) : null, [data]);

  return <div className="app-shell">
    <Sidebar />
    <main className="main-shell">
      <div className="flex min-h-[72px] items-center justify-between border-b border-[var(--border)] bg-white px-6">
        <div><p className="eyebrow">Meta Lead Ads attribution</p><p className="mt-1 text-sm text-[var(--muted)]">Exact campaign → CRM → ROBAWS outcomes</p></div>
        <div className="flex flex-wrap items-center gap-3">
          <label className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[var(--muted)]">
            Period
            <select className="h-10 border border-[var(--border)] bg-white px-3 text-sm font-medium normal-case tracking-normal text-[var(--ink)]" value={bootstrap.selectedMonth} onChange={event => setMonth(event.target.value)}>
              {bootstrap.availableMonths.map(value => <option key={value} value={value}>{campaignMonthLabel(value)}</option>)}
            </select>
          </label>
          <label className="flex items-center gap-3 text-xs font-semibold uppercase tracking-[.12em] text-[var(--muted)]">
            Company
            <select className="h-10 border border-[var(--border)] bg-white px-3 text-sm font-medium normal-case tracking-normal text-[var(--ink)]" value={companyId} onChange={event => setCompany(event.target.value)}>
              {bootstrap.companies.map(company => <option key={company.id} value={company.id}>{company.name}</option>)}
            </select>
          </label>
        </div>
      </div>
      <div className="page-wrap">
        <header className="page-header">
          <div><p className="eyebrow">Full-funnel campaign economics</p><h1>Campaigns</h1><p>{data ? `${data.company.name} · ${data.periodLabel}` : "Live Supabase data is required"}</p></div>
          <div className="company-mark bg-[var(--accent)]">{data?.company.shortName ?? "—"}</div>
        </header>

        {!data || !totals ? <EmptyCampaignState /> : <>
          <section className="mb-8 border-y border-[var(--border)] bg-white">
            <div className="grid grid-cols-2 divide-x divide-y divide-[var(--border)] md:grid-cols-4 xl:grid-cols-8 xl:divide-y-0">
              <Kpi label="Spend" value={formatCurrency(totals.spend, true)} />
              <Kpi label="Meta leads" value={formatNumber(totals.platformLeads)} />
              <Kpi label="CRM leads" value={formatNumber(totals.crmLeads)} />
              <Kpi label="Offers" value={formatNumber(totals.offers)} />
              <Kpi label="Pipeline" value={formatCurrency(totals.pipelineValue, true)} emphasis />
              <Kpi label="Won value" value={formatCurrency(totals.wonValue, true)} emphasis />
              <Kpi label="Invoiced" value={formatCurrency(totals.invoiced, true)} emphasis />
              <Kpi label="Paid" value={formatCurrency(totals.paid, true)} emphasis />
            </div>
          </section>

          <section className="mb-8 overflow-hidden border border-[var(--border)] bg-white">
            <div className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--border)] px-5 py-4">
              <div><p className="eyebrow">Campaign performance</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Money generated by campaign</h2></div>
              <p className="max-w-xl text-right text-xs leading-5 text-[var(--muted)]">Exact campaign rows use deterministic attribution. The “Meta CRM — campaign unknown” row keeps real CRM and ROBAWS outcomes visible until Meta supplies the campaign link.</p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full min-w-[1800px] border-collapse text-left text-xs">
                <thead className="bg-[#f7f8f5] text-[10px] uppercase tracking-[.1em] text-[var(--muted)]"><tr>
                  <Th>Campaign</Th><Th>Status</Th><Th number>Spend</Th><Th number>Impressions</Th><Th number>Clicks</Th><Th number>Meta leads</Th><Th number>CRM leads</Th><Th number>Appointments</Th><Th number>Offers</Th><Th number>Accepted</Th><Th number>Projects</Th><Th number>Project value</Th><Th number>Invoiced</Th><Th number>Paid</Th><Th number>CPL</Th><Th number>CAC</Th><Th number>Won ROAS</Th><Th number>Cash ROAS</Th>
                </tr></thead>
                <tbody>{data.campaigns.map(campaign => <CampaignRows key={campaign.id} campaign={campaign} expanded={expandedCampaignId === campaign.id} onToggle={() => setExpandedCampaignId(current => current === campaign.id ? null : campaign.id)} />)}</tbody>
              </table>
            </div>
          </section>

          <section className="mb-8 overflow-hidden border border-[var(--border)] bg-white">
            <div className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--border)] px-5 py-4">
              <div><p className="eyebrow">Known client value</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Which source produced a real client</h2></div>
              <p className="max-w-xl text-right text-xs leading-5 text-[var(--muted)]">Project value is shown when a safe ROBAWS project link exists. Invoiced and paid come from the ROBAWS client record. Exact campaign stays blank until a deterministic campaign link exists.</p>
            </div>
            {sourceClients.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs">
              <thead className="bg-[#f7f8f5] text-[10px] uppercase tracking-[.1em] text-[var(--muted)]"><tr><Th>Client</Th><Th>Source</Th><Th>Campaign</Th><Th>Client since</Th><Th number>Project value</Th><Th number>Invoiced</Th><Th number>Paid</Th><Th>Attribution</Th></tr></thead>
              <tbody>{sourceClients.map(client => <tr key={client.id} className="border-t border-[var(--border)]">
                <Td><span className="font-semibold">{client.name}</span></Td>
                <Td>{client.source}</Td>
                <Td>{client.campaign ?? "Unattributed"}</Td>
                <Td>{formatDate(client.clientSince)}</Td>
                <Td number>{client.projectValue === null ? "—" : formatCurrency(client.projectValue)}</Td>
                <Td number>{formatCurrency(client.invoiced)}</Td>
                <Td number><span className="font-semibold">{formatCurrency(client.paid)}</span></Td>
                <Td>{client.attribution}</Td>
              </tr>)}</tbody>
            </table></div> : <div className="p-6 text-sm text-[var(--muted)]">No commercial clients with a known source in this period.</div>}
          </section>

          <section className="border border-[var(--border)] bg-white">
            <div className="border-b border-[var(--border)] px-5 py-4"><p className="eyebrow">Attribution quality</p><h2 className="mt-1 text-lg font-semibold tracking-tight">Identity matching diagnostics</h2></div>
            <div className="grid grid-cols-2 divide-x divide-y divide-[var(--border)] md:grid-cols-4 xl:grid-cols-8 xl:divide-y-0">
              <Kpi label="Imported" value={formatNumber(data.quality.imported)} />
              <Kpi label="Matched" value={formatNumber(data.quality.matched)} />
              <Kpi label="Unmatched" value={formatNumber(data.quality.unmatched)} />
              <Kpi label="Ambiguous" value={formatNumber(data.quality.ambiguous)} />
              <Kpi label="Match rate" value={data.quality.matchRate === null ? "—" : `${formatNumber(data.quality.matchRate * 100)}%`} />
              <Kpi label="First lead" value={formatDate(data.quality.earliest)} />
              <Kpi label="Latest lead" value={formatDate(data.quality.latest)} />
              <Kpi label="Facebook unattributed" value={formatNumber(data.quality.unattributedFacebookLeads)} />
            </div>
            {data.quality.unattributedFacebookLeads > 0 ? <p className="border-t border-[var(--border)] bg-amber-50 px-5 py-3 text-xs text-amber-900">{data.quality.unattributedFacebookLeads} Meta/Facebook CRM lead(s) have no deterministic campaign link yet. Their real appointments, offers, accepted offers, projects and value are grouped in “Meta CRM — campaign unknown” instead of being hidden or guessed across campaigns.</p> : null}
          </section>
        </>}
      </div>
    </main>
  </div>;
}

function CampaignRows({ campaign, expanded, onToggle }: { campaign: MetaCampaignMetric; expanded: boolean; onToggle: () => void }) {
  return <>
    <tr className={`border-t border-[var(--border)] hover:bg-[#fbfcf8] ${campaign.id === "__meta_unattributed__" ? "bg-amber-50/60" : ""}`}>
      <td className={`sticky left-0 z-10 min-w-[260px] px-4 py-3 font-semibold ${campaign.id === "__meta_unattributed__" ? "bg-amber-50" : "bg-white"}`}><button type="button" className="flex w-full items-center gap-2 text-left" onClick={onToggle} aria-expanded={expanded}>{expanded ? <ChevronDown size={15} /> : <ChevronRight size={15} />}<span className="truncate">{campaign.name}</span></button></td>
      <Td>{campaign.status}</Td><Td number>{formatCurrency(campaign.spend)}</Td><Td number>{formatNumber(campaign.impressions)}</Td><Td number>{formatNumber(campaign.clicks)}</Td><Td number>{formatNumber(campaign.platformLeads)}</Td><Td number>{formatNumber(campaign.crmLeads)}</Td><Td number>{formatNumber(campaign.appointments)}</Td><Td number>{formatNumber(campaign.offers)}</Td><Td number>{formatNumber(campaign.acceptedOffers)}</Td><Td number>{formatNumber(campaign.projects)}</Td><Td number>{formatCurrency(campaign.projectValue)}</Td><Td number>{formatCurrency(campaign.invoiced)}</Td><Td number>{formatCurrency(campaign.paid)}</Td><Td number>{formatCurrency(campaign.cpl)}</Td><Td number>{formatCurrency(campaign.cac)}</Td><Td number>{ratio(campaign.wonRoas)}</Td><Td number>{ratio(campaign.cashRoas)}</Td>
    </tr>
    {expanded ? <tr><td colSpan={18} className="border-t border-[var(--border)] bg-[#f7f8f5] p-5"><CampaignDrilldown campaign={campaign} /></td></tr> : null}
  </>;
}

function CampaignDrilldown({ campaign }: { campaign: MetaCampaignMetric }) {
  return <div>
    <div className="mb-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[var(--muted)]">
      <span>Open offers <b className="text-[var(--ink)]">{campaign.openOffers}</b></span><span>Viewed <b className="text-[var(--ink)]">{campaign.viewedOffers}</b></span><span>Rejected <b className="text-[var(--ink)]">{campaign.rejectedOffers}</b></span><span>Open + won pipeline <b className="text-[var(--ink)]">{formatCurrency(campaign.pipelineValue)}</b></span><span>Pipeline ROAS <b className="text-[var(--ink)]">{ratio(campaign.pipelineRoas)}</b></span><span>Cost / appointment <b className="text-[var(--ink)]">{formatCurrency(campaign.costPerAppointment)}</b></span><span>Cost / offer <b className="text-[var(--ink)]">{formatCurrency(campaign.costPerOffer)}</b></span>
    </div>
    {campaign.leads.length === 0 ? <p className="border border-dashed border-[var(--border)] bg-white p-5 text-sm text-[var(--muted)]">No deterministically matched CRM leads for this campaign.</p> : <div className="overflow-x-auto border border-[var(--border)] bg-white"><table className="w-full min-w-[1750px] text-left text-xs"><thead className="bg-white text-[10px] uppercase tracking-[.1em] text-[var(--muted)]"><tr><Th>Lead</Th><Th>Created</Th><Th>Source</Th><Th>Campaign</Th><Th>Ad</Th><Th>CRM status</Th><Th>Appointment</Th><Th number>Offers</Th><Th>Latest status</Th><Th number>Offer value</Th><Th>Project status</Th><Th number>Project value</Th><Th number>Invoiced</Th><Th number>Paid</Th><Th>Attribution</Th></tr></thead><tbody>{campaign.leads.map(lead => <tr key={lead.id} className="border-t border-[var(--border)]"><Td><span className="font-semibold">{lead.name}</span></Td><Td>{formatDate(lead.createdAt)}</Td><Td>{lead.source}</Td><Td>{lead.campaign}</Td><Td>{lead.ad}</Td><Td>{lead.crmStatus}</Td><Td>{formatDate(lead.appointment)}</Td><Td number>{lead.offers}</Td><Td>{lead.latestOfferStatus ?? "—"}</Td><Td number>{formatCurrency(lead.latestOfferValue)}</Td><Td>{lead.projectStatus ?? "—"}</Td><Td number>{formatCurrency(lead.projectValue)}</Td><Td number>{formatCurrency(lead.invoiced)}</Td><Td number>{formatCurrency(lead.paid)}</Td><Td><span className="font-semibold">{lead.attributionMethod}</span><span className="ml-2 text-[var(--muted)]">{lead.attributionConfidence}</span></Td></tr>)}</tbody></table></div>}
  </div>;
}

function Kpi({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <div className="min-w-0 px-4 py-4"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[var(--muted)]">{label}</p><p className={`mt-2 truncate font-semibold tracking-tight ${emphasis ? "text-2xl" : "text-xl"}`}>{value}</p></div>; }
function Th({ children, number = false }: { children: React.ReactNode; number?: boolean }) { return <th className={`whitespace-nowrap px-4 py-3 font-semibold ${number ? "text-right" : ""}`}>{children}</th>; }
function Td({ children, number = false }: { children: React.ReactNode; number?: boolean }) { return <td className={`whitespace-nowrap px-4 py-3 ${number ? "text-right tabular-nums" : ""}`}>{children}</td>; }
function EmptyCampaignState() { return <div className="border border-dashed border-[var(--border)] bg-white p-10"><h2 className="text-xl font-semibold">Live data required</h2><p className="mt-2 max-w-xl text-sm text-[var(--muted)]">Connect Supabase and authorize a company to view exact Meta campaign attribution. No synthetic campaign or commercial values are shown.</p></div>; }
function ratio(value: number | null) { return value === null ? "—" : `${formatNumber(value)}×`; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("nl-BE", { timeZone: "Europe/Brussels", day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value)) : "—"; }

function totalCampaigns(campaigns: MetaCampaignMetric[]) {
  return campaigns.reduce((total, campaign) => ({
    spend: total.spend + campaign.spend,
    platformLeads: total.platformLeads + campaign.platformLeads,
    crmLeads: total.crmLeads + campaign.crmLeads,
    offers: total.offers + campaign.offers,
    pipelineValue: total.pipelineValue + campaign.pipelineValue,
    wonValue: total.wonValue + campaign.wonValue,
    invoiced: total.invoiced + campaign.invoiced,
    paid: total.paid + campaign.paid,
  }), { spend: 0, platformLeads: 0, crmLeads: 0, offers: 0, pipelineValue: 0, wonValue: 0, invoiced: 0, paid: 0 });
}


function campaignMonthLabel(value: string) {
  if (value === "ytd") return "Year to date";
  const [year, month] = value.split("-").map(Number);
  return new Intl.DateTimeFormat("en-BE", { month: "long", year: "numeric" }).format(new Date(Date.UTC(year, month - 1, 1)));
}
