"use client";

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from "recharts";
import type { TrendPoint } from "@/lib/data/types";
import { formatCurrency, formatNumber } from "@/lib/metrics/kpis";

const WAT_YELLOW = "#FFE100";
const WAT_BLACK = "#0A0A0A";
const tooltipStyle = { border: "1px solid #e7e7e2", borderRadius: 12, boxShadow: "0 18px 42px rgba(0,0,0,.10)", fontSize: 12 };

export function TrendChart({ data, metric, accent: _accent }: { data: TrendPoint[]; metric: keyof TrendPoint; accent: string }) {
  return <div className="h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="trendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={WAT_YELLOW} stopOpacity={.28}/><stop offset="100%" stopColor={WAT_YELLOW} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#eeeeea" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fill: "#72746f", fontSize: 12 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#72746f", fontSize: 12 }} tickFormatter={(value) => metric === "revenue" || metric === "spend" || metric === "cpl" || metric === "cac" ? formatCurrency(value, true) : formatNumber(value)}/><Tooltip contentStyle={tooltipStyle} formatter={(value) => [metric === "revenue" || metric === "spend" || metric === "cpl" || metric === "cac" ? formatCurrency(Number(value)) : formatNumber(Number(value)), metric]}/><Area type="monotone" dataKey={metric} stroke={WAT_BLACK} strokeWidth={2.4} fill="url(#trendFill)" activeDot={{ r: 4, strokeWidth: 0, fill: WAT_YELLOW }}/></AreaChart></ResponsiveContainer></div>;
}

export function ComparisonBars({ data, accent: _accent }: { data: { name: string; value: number; secondary?: number }[]; accent: string }) {
  return <div className="h-[260px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 10, right: 8, left: -12, bottom: 0 }}><CartesianGrid stroke="#eeeeea" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#72746f", fontSize: 11 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#72746f", fontSize: 11 }} tickFormatter={(v) => formatNumber(v)}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="value" fill={WAT_YELLOW} radius={[6,6,0,0]}/>{data.some(d => d.secondary !== undefined) && <Bar dataKey="secondary" fill={WAT_BLACK} radius={[6,6,0,0]}/>}</BarChart></ResponsiveContainer></div>;
}

export function MoneyTrendChart({ data }: { data: { label: string; paid: number; spend: number; complete: boolean }[] }) {
  return <div className="h-[280px] w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}><CartesianGrid stroke="#eeeeea" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "#777873", fontSize: 11 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#777873", fontSize: 11 }} tickFormatter={(value)=>formatCurrency(Number(value),true)}/><Tooltip contentStyle={tooltipStyle} formatter={(value,name)=>[formatCurrency(Number(value)),name==="paid"?"Paid value on invoices":"Dated marketing spend"]}/><Bar dataKey="paid" fill={WAT_BLACK} radius={[6,6,0,0]}/><Line type="monotone" dataKey="spend" stroke={WAT_YELLOW} strokeWidth={3} dot={{ r: 3, fill: WAT_YELLOW, stroke: WAT_BLACK, strokeWidth: 1 }}/></ComposedChart></ResponsiveContainer></div>;
}

export function QualityBars({ data }: { data: { name: string; value: number }[] }) {
  const colors = [WAT_YELLOW, WAT_BLACK, "#d8d8d4"];
  return <div className="h-[220px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ left: -22, right: 16 }}><XAxis type="number" hide/><YAxis type="category" dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#4e514d", fontSize: 12 }}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="value" radius={[0,2,2,0]}>{data.map((_, i) => <Cell key={i} fill={colors[i]}/>)}</Bar></BarChart></ResponsiveContainer></div>;
}


export function BusinessActivityChart({data,onMonthClick}:{data:Array<{month:string;label:string;won:number;invoiced:number;paid:number;spend:number;complete:boolean}>;onMonthClick?:(month:string)=>void}){
  const click=(state:unknown)=>{const chartState=state as {activePayload?:Array<{payload?:{month?:string}}>;activeLabel?:string|number}|null;const month=chartState?.activePayload?.[0]?.payload?.month??chartState?.activeLabel;if(month&&onMonthClick)onMonthClick(String(month));};
  return <div className="space-y-4">
    <div className="h-[270px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:12,right:12,left:0,bottom:0}} onClick={click}><CartesianGrid stroke="#eeeeea" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:11}} tickFormatter={(v)=>formatCurrency(Number(v),true)}/><Tooltip contentStyle={tooltipStyle} formatter={(value,name)=>[formatCurrency(Number(value)),name==="won"?"Won project value":name==="invoiced"?"Invoiced":"Paid value on invoices"]}/><Bar dataKey="won" fill={WAT_YELLOW} radius={[5,5,0,0]}/><Bar dataKey="invoiced" fill="#7f7f78" radius={[5,5,0,0]}/><Bar dataKey="paid" fill={WAT_BLACK} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div>
    <div className="h-[130px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:6,right:12,left:0,bottom:0}} onClick={click}><CartesianGrid stroke="#eeeeea" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:10}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:10}} tickFormatter={(v)=>formatCurrency(Number(v),true)}/><Tooltip contentStyle={tooltipStyle} formatter={(value)=>[formatCurrency(Number(value)),"Dated marketing spend"]}/><Area type="monotone" dataKey="spend" stroke={WAT_YELLOW} strokeWidth={2.5} fill={WAT_YELLOW} fillOpacity={.12}/></AreaChart></ResponsiveContainer></div>
  </div>;
}

export function CostOutcomeChart({data}:{data:Array<{name:string;value:number|null}>}){
  const rows=data.filter(item=>item.value!==null);
  if(!rows.length)return <div className="chart-empty">Cost-based metrics are unavailable until paid-source spend is complete.</div>;
  return <div className="h-[260px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{left:10,right:28,top:6,bottom:0}}><CartesianGrid stroke="#eeeeea" horizontal={false}/><XAxis type="number" axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:10}} tickFormatter={(v)=>formatCurrency(Number(v),true)}/><YAxis type="category" dataKey="name" width={105} axisLine={false} tickLine={false} tick={{fill:"#4e514d",fontSize:11}}/><Tooltip contentStyle={tooltipStyle} formatter={(value)=>[formatCurrency(Number(value)),"Cost"]}/><Bar dataKey="value" fill={WAT_YELLOW} radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div>;
}

export function SourcePerformanceChart({data,onSourceClick}:{data:Array<{source:string;spend:number|null;paid:number;customers:number}>;onSourceClick?:(source:string)=>void}){
  const rows=data;
  if(!rows.length)return <div className="chart-empty">No source performance is available for this period.</div>;
  return <div className="h-[320px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{left:24,right:18,top:8,bottom:0}} onClick={(state:unknown)=>{const chartState=state as {activePayload?:Array<{payload?:{source?:string}}>};const source=chartState?.activePayload?.[0]?.payload?.source;if(source&&onSourceClick)onSourceClick(source)}}><CartesianGrid stroke="#eeeeea" horizontal={false}/><XAxis type="number" axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:10}} tickFormatter={(v)=>formatCurrency(Number(v),true)}/><YAxis type="category" dataKey="source" width={125} axisLine={false} tickLine={false} tick={{fill:"#4e514d",fontSize:11}}/><Tooltip contentStyle={tooltipStyle} formatter={(value,name)=>[value===null||value===undefined?"Cost missing":formatCurrency(Number(value)),name==="paid"?"Paid value":"Spend"]} labelFormatter={(label,payload)=>{const customers=payload?.[0]?.payload?.customers;return customers===undefined?String(label):`${label} · ${customers} customer(s)`;}}/><Bar dataKey="spend" fill={WAT_YELLOW} radius={[0,5,5,0]}/><Bar dataKey="paid" fill={WAT_BLACK} radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div>;
}

export function SourceDecisionQuadrant({data}:{data:Array<{source:string;cac:number|null;paid:number;customers:number}>}){
  const rows=data.filter(item=>item.cac!==null&&Number.isFinite(item.cac)&&item.paid>0).map(item=>({...item,cac:Number(item.cac)}));
  if(rows.length<2)return <div className="chart-empty">At least two sources with known CAC and paid value are required for the source quadrant.</div>;
  const med=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);const mid=Math.floor(sorted.length/2);return sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2;};
  const medianCac=med(rows.map(item=>item.cac));
  const medianPaid=med(rows.map(item=>item.paid));
  return <div>
    <div className="h-[330px] w-full"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:18,right:24,left:0,bottom:10}}><CartesianGrid stroke="#eeeeea"/><XAxis type="number" dataKey="cac" name="Cohort CAC" axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:10}} tickFormatter={(v)=>formatCurrency(Number(v),true)} label={{value:"Cohort CAC →",position:"insideBottomRight",offset:-4,fill:"#777873",fontSize:10}}/><YAxis type="number" dataKey="paid" name="Paid value" axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:10}} tickFormatter={(v)=>formatCurrency(Number(v),true)}/><ZAxis type="number" dataKey="customers" range={[90,260]} name="Customers"/><Tooltip cursor={{strokeDasharray:"3 3"}} content={(props:unknown)=>{const tooltip=props as {active?:boolean;payload?:Array<{payload?:{source:string;cac:number;paid:number;customers:number}}>};const row=tooltip?.payload?.[0]?.payload;if(!tooltip?.active||!row)return null;return <div className="chart-tooltip"><strong>{row.source}</strong><span>CAC {formatCurrency(row.cac)}</span><span>Paid value {formatCurrency(row.paid)}</span><span>{formatNumber(row.customers)} customer(s)</span></div>;}}/><ReferenceLine x={medianCac} stroke="#a4a49d" strokeDasharray="4 4" label={{value:"Median CAC",position:"insideTopRight",fill:"#777873",fontSize:10}}/><ReferenceLine y={medianPaid} stroke="#a4a49d" strokeDasharray="4 4" label={{value:"Median paid value",position:"insideTopLeft",fill:"#777873",fontSize:10}}/><Scatter data={rows} fill={WAT_YELLOW}>{rows.map((item,index)=><Cell key={item.source} fill={index%2===0?WAT_YELLOW:WAT_BLACK}/>)}</Scatter></ScatterChart></ResponsiveContainer></div>
    <p className="chart-footnote">Reference lines are sample medians, not performance targets. Sources with missing cost are excluded rather than plotted at €0.</p>
  </div>;
}

export function CohortPaybackChart({data,spendReference}:{data:Array<{monthOffset:number;label:string;cumulativePaid:number}>;spendReference:number|null}){
  if(!data.length)return <div className="chart-empty">No invoice-linked paid value is available for this cohort yet.</div>;
  return <div className="h-[290px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:14,right:14,left:0,bottom:0}}><defs><linearGradient id="paybackFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={WAT_YELLOW} stopOpacity={.34}/><stop offset="100%" stopColor={WAT_YELLOW} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#eeeeea" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#777873",fontSize:11}} tickFormatter={(v)=>formatCurrency(Number(v),true)}/><Tooltip contentStyle={tooltipStyle} formatter={(value)=>[formatCurrency(Number(value)),"Cumulative paid value attached to invoices"]}/>{spendReference!==null&&<ReferenceLine y={spendReference} stroke="#777873" strokeDasharray="4 4" label={{value:"Covered acquisition spend",position:"insideTopRight",fill:"#777873",fontSize:10}}/>}<Area type="monotone" dataKey="cumulativePaid" stroke={WAT_BLACK} strokeWidth={2.5} fill="url(#paybackFill)" activeDot={{r:4,fill:WAT_YELLOW,stroke:WAT_BLACK,strokeWidth:1}}/></AreaChart></ResponsiveContainer></div>;
}
