"use client";

import { useState } from "react";
import { AlertCircle, Check, ChevronDown, ExternalLink, RefreshCw, ShieldCheck } from "lucide-react";
import type { CampaignMetric, CompanyDataset } from "@/lib/data/types";
import { calculateKpis, formatCurrency, formatNumber, formatPercent, percentage, safeDivide } from "@/lib/metrics/kpis";
import { ComparisonBars, TrendChart } from "./charts";
import { Card, EmptyState, KpiCard, SectionHeader, StatusPill } from "./ui";

export function AcquisitionPage({ data }: { data: CompanyDataset }) {
  const paid = data.channels.filter(c => c.spend > 0);
  const spend = paid.reduce((s,c)=>s+c.spend,0), impressions=paid.reduce((s,c)=>s+c.impressions,0), clicks=paid.reduce((s,c)=>s+c.clicks,0), platform=paid.reduce((s,c)=>s+c.platformConversions,0), leads=paid.reduce((s,c)=>s+c.leads,0), won=paid.reduce((s,c)=>s+c.won,0), revenue=paid.reduce((s,c)=>s+c.revenue,0);
  return <div className="space-y-6"><div className="kpi-grid kpi-grid-six border-l border-t border-[var(--line)]"><KpiCard label="Paid media spend" value={formatCurrency(spend,true)} delta={6.4}/><KpiCard label="Impressions" value={formatNumber(impressions)} meta={`${formatCurrency(safeDivide(spend,impressions/1000))} CPM`}/><KpiCard label="Clicks" value={formatNumber(clicks)} meta={`${formatPercent(percentage(clicks,impressions))} CTR`}/><KpiCard label="Platform conversions" value={formatNumber(platform)} meta="Ad-platform reported"/><KpiCard label="CRM leads" value={formatNumber(leads)} meta={`${formatCurrency(safeDivide(spend,leads))} CPL`}/><KpiCard label="CRM-confirmed won" value={formatNumber(won)} meta={`${formatNumber(safeDivide(revenue,spend))}× ROAS`}/></div><div className="callout"><AlertCircle size={18}/><div><strong>Platform conversions are directional.</strong><p>They are shown separately from CRM-confirmed leads, visits, customers, and revenue.</p></div></div><div className="grid gap-6 xl:grid-cols-2"><Card className="p-5"><SectionHeader title="Spend vs attributed revenue" description="Paid channels only"/><ComparisonBars accent={data.company.accent} data={paid.map(c=>({name:c.channel.replace(" Ads",""),value:c.spend,secondary:c.revenue}))}/></Card><Card className="p-5"><SectionHeader title="Qualified lead cost trend" description="Efficiency after lead validation"/><TrendChart data={data.trend} metric="cpl" accent={data.company.accent}/></Card></div><Card className="p-5"><SectionHeader title="Paid channel detail" description="Marketing delivery alongside CRM-confirmed outcomes"/><div className="table-scroll"><table><thead><tr><th>Channel</th><th>Spend</th><th>Impressions</th><th>Clicks</th><th>CTR</th><th>CPC</th><th>Platform conv.</th><th>CRM leads</th><th>Qualified</th><th>Visits</th><th>Won</th><th>Revenue</th><th>CAC</th><th>ROAS</th></tr></thead><tbody>{paid.map(row=>{const k=calculateKpis(row);return <tr key={row.id}><td className="font-semibold">{row.channel}</td><td>{formatCurrency(row.spend)}</td><td>{formatNumber(row.impressions)}</td><td>{formatNumber(row.clicks)}</td><td>{formatPercent(percentage(row.clicks,row.impressions))}</td><td>{formatCurrency(safeDivide(row.spend,row.clicks))}</td><td>{row.platformConversions}</td><td>{row.leads}</td><td>{row.qualified}</td><td>{row.visits}</td><td>{row.won}</td><td>{formatCurrency(row.revenue)}</td><td>{formatCurrency(k.cac)}</td><td>{k.roas===null?"—":`${formatNumber(k.roas)}×`}</td></tr>})}</tbody></table></div></Card></div>;
}

export function ServicesPage({ data }: { data: CompanyDataset }) {
  const top=[...data.services].sort((a,b)=>b.revenue-a.revenue)[0];
  return <div className="space-y-6"><div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card className="p-5"><SectionHeader title="Revenue by service" description="Commercial value, not lead volume alone"/><ComparisonBars accent={data.company.accent} data={data.services.slice(0,6).map(s=>({name:s.name.split(" ")[0],value:s.revenue}))}/></Card><Card className="p-5"><SectionHeader title="Strongest outcome"/><p className="text-xs font-bold uppercase tracking-[.12em] text-[var(--muted)]">Highest attributed revenue</p><p className="mt-3 text-3xl font-semibold tracking-tight">{top?.name ?? "—"}</p><p className="mt-2 text-lg text-[var(--muted)]">{top ? formatCurrency(top.revenue,true) : "—"}</p><div className="mt-8 border-t border-[var(--line)] pt-5"><p className="text-sm leading-6 text-[var(--muted)]">A cheap lead is not automatically a good lead. This view ranks services by won revenue, acquisition cost, and margin together.</p></div></Card></div><Card className="p-5"><SectionHeader title="Service economics" description="Database-driven service catalogue for the selected company"/><div className="table-scroll"><table><thead><tr><th>Service</th><th>Spend</th><th>Leads</th><th>Qualified</th><th>Visits</th><th>Quotes</th><th>Won</th><th>Revenue</th><th>Avg. project</th><th>CPL</th><th>CAC</th><th>ROAS</th><th>Gross margin</th></tr></thead><tbody>{data.services.map(row=>{const k=calculateKpis(row);return <tr key={row.id}><td className="font-semibold">{row.name}</td><td>{formatCurrency(row.spend)}</td><td>{row.leads}</td><td>{row.qualified}</td><td>{row.visits}</td><td>{row.quotes}</td><td>{row.won}</td><td>{formatCurrency(row.revenue)}</td><td>{formatCurrency(safeDivide(row.revenue,row.won))}</td><td>{formatCurrency(k.cpl)}</td><td>{formatCurrency(k.cac)}</td><td>{k.roas===null?"—":`${formatNumber(k.roas)}×`}</td><td>{row.grossMargin===null?"—":`${row.grossMargin}%`}</td></tr>})}</tbody></table></div></Card></div>;
}

export function CampaignsPage({ data }: { data: CompanyDataset }) {
  const [open,setOpen]=useState<string|null>(data.campaigns[0]?.id??null);
  return <div className="space-y-6"><Card className="p-5"><SectionHeader title="Campaign performance" description="Click a campaign to inspect its hierarchy"/><div className="table-scroll"><table><thead><tr><th>Campaign</th><th>Channel</th><th>Spend</th><th>Impressions</th><th>Clicks</th><th>CTR</th><th>CPC</th><th>Leads</th><th>Qualified</th><th>Visits</th><th>Won</th><th>Revenue</th><th>CAC</th><th>ROAS</th></tr></thead><tbody>{data.campaigns.map(row=><CampaignRow key={row.id} row={row} open={open===row.id} toggle={()=>setOpen(open===row.id?null:row.id)}/>)}</tbody></table></div></Card><div className="grid gap-6 xl:grid-cols-2"><Card className="p-5"><SectionHeader title="Creative angles" description="Ranked by customers and revenue, not CTR alone"/><div className="space-y-1">{[...data.campaigns].sort((a,b)=>b.revenue-a.revenue).map((c,i)=><div className="grid grid-cols-[28px_1fr_auto] items-center gap-3 border-b border-[var(--line)] py-3 last:border-0" key={c.id}><span className="text-sm text-[var(--muted)]">0{i+1}</span><div><p className="text-sm font-semibold capitalize">{c.angle}</p><p className="text-xs text-[var(--muted)]">{c.leads} leads · {c.qualified} qualified · {c.won} customers</p></div><span className="text-sm font-semibold">{formatCurrency(c.revenue,true)}</span></div>)}</div></Card><Card className="p-5"><SectionHeader title="Revenue by campaign" description="Marketing-attributed CRM revenue"/><ComparisonBars data={data.campaigns.map(c=>({name:c.name.split(" — ")[0],value:c.revenue}))} accent={data.company.accent}/></Card></div></div>;
}

function CampaignRow({row,open,toggle}:{row:CampaignMetric;open:boolean;toggle:()=>void}) { const k=calculateKpis(row); return <><tr onClick={toggle} className="cursor-pointer"><td className="font-semibold"><span className="inline-flex items-center gap-2"><ChevronDown size={14} className={open?"rotate-180":""}/>{row.name}</span></td><td>{row.channel}</td><td>{formatCurrency(row.spend)}</td><td>{formatNumber(row.impressions)}</td><td>{formatNumber(row.clicks)}</td><td>{formatPercent(percentage(row.clicks,row.impressions))}</td><td>{formatCurrency(safeDivide(row.spend,row.clicks))}</td><td>{row.leads}</td><td>{row.qualified}</td><td>{row.visits}</td><td>{row.won}</td><td>{formatCurrency(row.revenue)}</td><td>{formatCurrency(k.cac)}</td><td>{k.roas===null?"—":`${formatNumber(k.roas)}×`}</td></tr>{open&&<tr className="drill-row"><td colSpan={14}><div className="flex flex-wrap items-center gap-4 py-2 pl-7 text-sm"><StatusPill tone="neutral">{row.childLabel}</StatusPill><span>Creative angle: <strong className="capitalize">{row.angle}</strong></span><span>Qualified rate: <strong>{formatPercent(percentage(row.qualified,row.leads))}</strong></span><span>Sales rate: <strong>{formatPercent(percentage(row.won,row.leads))}</strong></span></div></td></tr>}</>; }

export function WebsiteSeoPage({ data }: { data: CompanyDataset }) {
  const w=data.website,s=data.seo;
  return <div className="space-y-6"><div className="kpi-grid kpi-grid-six border-l border-t border-[var(--line)]"><KpiCard label="Users" value={formatNumber(w.users)}/><KpiCard label="Sessions" value={formatNumber(w.sessions)} delta={8.2}/><KpiCard label="Engaged sessions" value={formatNumber(w.engagedSessions)} meta={formatPercent(percentage(w.engagedSessions,w.sessions))}/><KpiCard label="Form submissions" value={formatNumber(w.formSubmissions)}/><KpiCard label="WhatsApp + phone" value={formatNumber(w.whatsappClicks+w.phoneClicks)}/><KpiCard label="Website conversion" value={formatPercent(percentage(w.quoteRequests,w.sessions))} meta="Quote requests / sessions"/></div><div className="grid gap-6 xl:grid-cols-2"><Card className="p-5"><SectionHeader title="Sessions trend" description="GA4-style website performance"/><TrendChart data={data.trend} metric="sessions" accent={data.company.accent}/></Card><Card className="p-5"><SectionHeader title="Search performance" description="Google Search Console"/><div className="grid grid-cols-2 gap-px bg-[var(--line)]"><Mini label="Impressions" value={formatNumber(s.impressions)}/><Mini label="Clicks" value={formatNumber(s.clicks)}/><Mini label="CTR" value={formatPercent(s.ctr)}/><Mini label="Avg. position" value={formatNumber(s.position)}/></div><div className="mt-5"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-[var(--muted)]">Branded vs non-branded</p><div className="flex h-3 overflow-hidden bg-slate-100"><div className="bg-[var(--ink)]" style={{width:`${s.brandedShare}%`}}/><div className="bg-[var(--accent)]" style={{width:`${100-s.brandedShare}%`}}/></div><div className="mt-2 flex justify-between text-xs text-[var(--muted)]"><span>{s.brandedShare}% branded</span><span>{100-s.brandedShare}% non-branded</span></div></div></Card></div><Card className="p-5"><SectionHeader title="Google Business Profile" description="No API data is fabricated"/><EmptyState title="Google Business Profile not connected" body="Connect the profile to load views, website clicks, calls, direction requests, searches, reviews, and average rating."/></Card></div>;
}

export function LocationsPage({ data }: { data: CompanyDataset }) {
  return <div className="space-y-6"><div className="grid gap-6 xl:grid-cols-[1fr_1fr]"><Card className="p-5"><SectionHeader title="Qualified leads by municipality" description="Comparison around Antwerp"/><ComparisonBars data={data.locations.map(l=>({name:l.municipality,value:l.qualified}))} accent={data.company.accent}/></Card><Card className="p-5"><SectionHeader title="Revenue by municipality" description="CRM-confirmed project value"/><ComparisonBars data={data.locations.map(l=>({name:l.municipality,value:l.revenue}))} accent="#191c1f"/></Card></div><Card className="p-5"><SectionHeader title="Location economics" description="Table-first geographic analysis for reliable MVP reporting"/><div className="table-scroll"><table><thead><tr><th>Municipality</th><th>Leads</th><th>Qualified</th><th>Won projects</th><th>Revenue</th><th>Avg. project</th><th>CPL</th><th>CAC</th></tr></thead><tbody>{data.locations.map(row=><tr key={row.municipality}><td className="font-semibold">{row.municipality}</td><td>{row.leads}</td><td>{row.qualified}</td><td>{row.won}</td><td>{formatCurrency(row.revenue)}</td><td>{formatCurrency(safeDivide(row.revenue,row.won))}</td><td>{formatCurrency(safeDivide(row.spend,row.leads))}</td><td>{formatCurrency(safeDivide(row.spend,row.won))}</td></tr>)}</tbody></table></div></Card></div>;
}

export function IntegrationsPage({ data }: { data: CompanyDataset }) {
  const h=data.dataHealth;
  return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.integrations.map(item=><Card className="p-5" key={item.id}><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center bg-[var(--surface)]"><RefreshCw size={18}/></div><StatusPill tone={item.status==="Connected"?"good":item.status==="Error"?"bad":"neutral"}>{item.status}</StatusPill></div><h3 className="mt-5 font-semibold">{item.name}</h3><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt className="text-[var(--muted)]">Last successful sync</dt><dd>{item.lastSuccess??"Never"}</dd></div><div className="flex justify-between"><dt className="text-[var(--muted)]">Last attempted</dt><dd>{item.lastAttempt??"Never"}</dd></div><div className="flex justify-between"><dt className="text-[var(--muted)]">Records imported</dt><dd>{item.records}</dd></div></dl><div className="mt-5 flex gap-2"><button className="button-primary" disabled={item.status!=="Connected"}><RefreshCw size={14}/> Sync</button><button className="button-secondary">Configure <ExternalLink size={13}/></button></div></Card>)}</div><Card className="p-5"><SectionHeader title="Data health audit" description="Issues are exposed instead of silently guessed"/><div className="grid gap-px bg-[var(--line)] sm:grid-cols-2 xl:grid-cols-4"><Mini label="Leads missing source" value={String(h.missingSource)}/><Mini label="Missing service" value={String(h.missingService)}/><Mini label="Missing campaign" value={String(h.missingCampaign)}/><Mini label="Won without revenue" value={String(h.wonMissingRevenue)}/><Mini label="Potential duplicates" value={String(h.duplicates)}/><Mini label="Campaigns without spend" value={String(h.campaignsWithoutSpend)}/><Mini label="Days since sync" value={h.daysSinceSync===null?"—":String(h.daysSinceSync)}/><Mini label="Schema status" value="Ready"/></div></Card></div>;
}

export function SettingsPage({ data }: { data: CompanyDataset }) {
  return <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><SectionHeader title="Company settings" description="Reporting configuration for this client"/><div className="form-grid"><Field label="Company name" value={data.company.name}/><Field label="Currency" value="EUR — Euro"/><Field label="Timezone" value="Europe/Brussels"/><Field label="Default attribution" value="First touch"/><Field label="Reporting margin" value="Use service-level margin"/><Field label="Data retention" value="No automatic deletion"/></div><button className="button-primary mt-6"><Check size={15}/> Save changes</button></Card><Card className="p-5"><SectionHeader title="Access model"/><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center bg-[var(--accent-soft)]"><ShieldCheck size={18}/></div><div><p className="font-semibold">Row-level company isolation</p><p className="mt-1 text-sm leading-6 text-[var(--muted)]">Agency admins can access all organization companies. Client users only see companies assigned through company_users.</p></div></div><div className="mt-6 space-y-3">{["super_admin","agency_admin","company_admin","viewer"].map((role,i)=><div className="flex items-center justify-between border-b border-[var(--line)] py-3 text-sm" key={role}><span className="font-medium">{role}</span><span className="text-[var(--muted)]">{i<2?"Agency scope":"Assigned companies"}</span></div>)}</div></Card></div>;
}

function Mini({label,value}:{label:string;value:string}) { return <div className="bg-white p-4"><p className="text-xs uppercase tracking-wide text-[var(--muted)]">{label}</p><p className="mt-3 text-xl font-semibold">{value}</p></div>; }
function Field({label,value}:{label:string;value:string}) { return <label><span>{label}</span><input value={value} readOnly/></label>; }
