create table if not exists public.reporting_change_events (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  provider text not null,
  sync_log_id bigint references public.sync_logs(id) on delete set null,
  occurred_at timestamptz not null default now(),
  metric_key text not null,
  title text not null,
  detail text,
  delta numeric,
  before_value numeric,
  after_value numeric,
  severity text not null default 'info' check (severity in ('info','good','warn','bad')),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists reporting_change_events_company_time_idx
  on public.reporting_change_events(company_id, occurred_at desc);
create index if not exists reporting_change_events_provider_time_idx
  on public.reporting_change_events(company_id, provider, occurred_at desc);

alter table public.reporting_change_events enable row level security;

drop policy if exists "authorized users can read reporting change events" on public.reporting_change_events;
create policy "authorized users can read reporting change events"
on public.reporting_change_events for select to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = (select auth.uid())
      and (
        (
          u.role in ('super_admin','agency_admin')
          and exists (
            select 1 from public.companies c
            where c.id = reporting_change_events.company_id
              and c.organization_id = u.organization_id
          )
        )
        or exists (
          select 1 from public.company_users cu
          where cu.user_id = u.id
            and cu.company_id = reporting_change_events.company_id
        )
      )
  )
);

grant select on public.reporting_change_events to authenticated;

create table if not exists public.reporting_overrides (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  period_key text not null,
  scope_type text not null check (scope_type in ('company','source','client')),
  scope_key text not null,
  field_key text not null,
  value jsonb not null,
  note text,
  updated_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, period_key, scope_type, scope_key, field_key)
);

create index if not exists reporting_overrides_company_period_idx
  on public.reporting_overrides(company_id, period_key);

alter table public.reporting_overrides enable row level security;

drop policy if exists "authorized users can read reporting overrides" on public.reporting_overrides;
create policy "authorized users can read reporting overrides"
on public.reporting_overrides for select to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = (select auth.uid())
      and (
        (
          u.role in ('super_admin','agency_admin')
          and exists (
            select 1 from public.companies c
            where c.id = reporting_overrides.company_id
              and c.organization_id = u.organization_id
          )
        )
        or exists (
          select 1 from public.company_users cu
          where cu.user_id = u.id
            and cu.company_id = reporting_overrides.company_id
        )
      )
  )
);

drop policy if exists "authorized users can insert reporting overrides" on public.reporting_overrides;
create policy "authorized users can insert reporting overrides"
on public.reporting_overrides for insert to authenticated
with check (
  updated_by = (select auth.uid())
  and exists (
    select 1 from public.users u
    where u.id = (select auth.uid())
      and (
        (
          u.role in ('super_admin','agency_admin')
          and exists (
            select 1 from public.companies c
            where c.id = reporting_overrides.company_id
              and c.organization_id = u.organization_id
          )
        )
        or exists (
          select 1 from public.company_users cu
          where cu.user_id = u.id
            and cu.company_id = reporting_overrides.company_id
        )
      )
  )
);

drop policy if exists "authorized users can update reporting overrides" on public.reporting_overrides;
create policy "authorized users can update reporting overrides"
on public.reporting_overrides for update to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = (select auth.uid())
      and (
        (
          u.role in ('super_admin','agency_admin')
          and exists (
            select 1 from public.companies c
            where c.id = reporting_overrides.company_id
              and c.organization_id = u.organization_id
          )
        )
        or exists (
          select 1 from public.company_users cu
          where cu.user_id = u.id
            and cu.company_id = reporting_overrides.company_id
        )
      )
  )
)
with check (updated_by = (select auth.uid()));

drop policy if exists "authorized users can delete reporting overrides" on public.reporting_overrides;
create policy "authorized users can delete reporting overrides"
on public.reporting_overrides for delete to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = (select auth.uid())
      and (
        (
          u.role in ('super_admin','agency_admin')
          and exists (
            select 1 from public.companies c
            where c.id = reporting_overrides.company_id
              and c.organization_id = u.organization_id
          )
        )
        or exists (
          select 1 from public.company_users cu
          where cu.user_id = u.id
            and cu.company_id = reporting_overrides.company_id
        )
      )
  )
);

grant select, insert, update, delete on public.reporting_overrides to authenticated;

create table if not exists public.reporting_automation_settings (
  company_id uuid primary key references public.companies(id) on delete cascade,
  enabled boolean not null default true,
  token_sha256 text not null,
  operational_schedule text not null default '0 * * * *',
  marketing_schedule text not null default '17 */3 * * *',
  updated_at timestamptz not null default now()
);

alter table public.reporting_automation_settings enable row level security;

drop policy if exists "authorized users can read reporting automation settings" on public.reporting_automation_settings;
create policy "authorized users can read reporting automation settings"
on public.reporting_automation_settings for select to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = (select auth.uid())
      and (
        (
          u.role in ('super_admin','agency_admin')
          and exists (
            select 1 from public.companies c
            where c.id = reporting_automation_settings.company_id
              and c.organization_id = u.organization_id
          )
        )
        or exists (
          select 1 from public.company_users cu
          where cu.user_id = u.id
            and cu.company_id = reporting_automation_settings.company_id
        )
      )
  )
);

grant select on public.reporting_automation_settings to authenticated;
