create extension if not exists pgcrypto;
create schema if not exists reporting_private;

create type public.app_role as enum ('super_admin', 'agency_admin', 'company_admin', 'viewer');
create type public.lead_quality as enum ('A', 'B', 'C');
create type public.sales_stage as enum ('new', 'contacted', 'qualified', 'visit_booked', 'visit_completed', 'quote_sent', 'won', 'lost');
create type public.integration_status as enum ('connected', 'not_connected', 'error');
create type public.attribution_model as enum ('first_touch', 'last_touch', 'multi_touch');

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table public.companies (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  slug text not null unique,
  currency text not null default 'EUR',
  timezone text not null default 'Europe/Brussels',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  full_name text,
  role public.app_role not null default 'viewer',
  created_at timestamptz not null default now()
);

create table public.company_users (
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (company_id, user_id)
);

create table public.services (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  default_gross_margin numeric(7,4),
  unique (company_id, name)
);

create table public.marketing_channels (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  channel_type text not null,
  is_paid boolean not null default false,
  unique (organization_id, name)
);

create table public.campaigns (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  channel_id uuid not null references public.marketing_channels(id),
  external_id text,
  name text not null,
  status text,
  started_at date,
  ended_at date,
  unique (company_id, channel_id, external_id)
);

create table public.ad_groups (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  external_id text,
  name text not null,
  group_type text not null default 'ad_group',
  unique (campaign_id, external_id)
);

create table public.ads (
  id uuid primary key default gen_random_uuid(),
  ad_group_id uuid not null references public.ad_groups(id) on delete cascade,
  external_id text,
  name text not null,
  status text,
  unique (ad_group_id, external_id)
);

create table public.creative_metadata (
  id uuid primary key default gen_random_uuid(),
  ad_id uuid not null unique references public.ads(id) on delete cascade,
  service_id uuid references public.services(id),
  creative_name text not null,
  creative_type text,
  angle text,
  hook text,
  format text
);

create table public.daily_marketing_metrics (
  id bigint generated by default as identity primary key,
  date date not null,
  company_id uuid not null references public.companies(id) on delete cascade,
  channel_id uuid not null references public.marketing_channels(id),
  campaign_id uuid references public.campaigns(id),
  ad_group_id uuid references public.ad_groups(id),
  ad_id uuid references public.ads(id),
  service_id uuid references public.services(id),
  spend numeric(14,2) not null default 0 check (spend >= 0),
  impressions bigint not null default 0 check (impressions >= 0),
  reach bigint not null default 0 check (reach >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  landing_page_views bigint not null default 0 check (landing_page_views >= 0),
  platform_conversions numeric(12,2) not null default 0 check (platform_conversions >= 0),
  unique nulls not distinct (date, company_id, channel_id, campaign_id, ad_group_id, ad_id, service_id)
);

create table public.website_metrics (
  id bigint generated by default as identity primary key,
  date date not null,
  company_id uuid not null references public.companies(id) on delete cascade,
  landing_page text,
  source text,
  medium text,
  device_category text,
  users bigint not null default 0,
  sessions bigint not null default 0,
  new_users bigint not null default 0,
  engaged_sessions bigint not null default 0,
  form_submissions bigint not null default 0,
  whatsapp_clicks bigint not null default 0,
  phone_clicks bigint not null default 0,
  quote_requests bigint not null default 0
);

create table public.seo_metrics (
  id bigint generated by default as identity primary key,
  date date not null,
  company_id uuid not null references public.companies(id) on delete cascade,
  query text,
  page text,
  is_branded boolean,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  position_sum numeric(16,4) not null default 0
);

create table public.gbp_metrics (
  id bigint generated by default as identity primary key,
  date date not null,
  company_id uuid not null references public.companies(id) on delete cascade,
  profile_views bigint not null default 0,
  website_clicks bigint not null default 0,
  calls bigint not null default 0,
  direction_requests bigint not null default 0,
  messages bigint not null default 0,
  searches bigint not null default 0,
  reviews bigint not null default 0,
  rating_sum numeric(12,2) not null default 0
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  created_at timestamptz not null default now(),
  name text not null,
  email text,
  phone text,
  source text,
  channel_id uuid references public.marketing_channels(id),
  campaign_id uuid references public.campaigns(id),
  ad_id uuid references public.ads(id),
  service_id uuid references public.services(id),
  municipality text,
  postal_code text,
  lead_quality public.lead_quality,
  sales_stage public.sales_stage not null default 'new',
  assigned_to uuid references public.users(id),
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  gclid text,
  fbclid text,
  meta_lead_id text,
  notes text,
  first_contacted_at timestamptz,
  closed_at timestamptz,
  lost_reason text
);

create table public.lead_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references public.leads(id) on delete cascade,
  event_type text not null,
  from_stage public.sales_stage,
  to_stage public.sales_stage,
  notes text,
  occurred_at timestamptz not null default now(),
  created_by uuid references public.users(id)
);

create table public.appointments (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads(id) on delete cascade,
  scheduled_at timestamptz not null,
  completed_at timestamptz,
  status text not null,
  no_show boolean not null default false,
  notes text
);

create table public.quotes (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads(id) on delete cascade,
  quote_number text not null,
  quote_value numeric(14,2) not null check (quote_value >= 0),
  created_at timestamptz not null default now(),
  status text not null,
  accepted_at timestamptz,
  unique (lead_id, quote_number)
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads(id) on delete restrict,
  service_id uuid references public.services(id),
  project_value numeric(14,2),
  gross_margin numeric(7,4),
  status text not null,
  won_at timestamptz,
  completed_at timestamptz
);

create table public.revenue_attribution (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  channel_id uuid references public.marketing_channels(id),
  campaign_id uuid references public.campaigns(id),
  model public.attribution_model not null default 'first_touch',
  attributed_revenue numeric(14,2) not null check (attributed_revenue >= 0),
  weight numeric(7,6) not null default 1 check (weight >= 0 and weight <= 1),
  attributed_at timestamptz not null default now()
);

create table public.reporting_integration_connections (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  provider text not null,
  status public.integration_status not null default 'not_connected',
  configuration jsonb not null default '{}'::jsonb,
  last_successful_sync timestamptz,
  last_attempted_sync timestamptz,
  created_at timestamptz not null default now(),
  unique (company_id, provider)
);

create table reporting_private.integration_secrets (
  integration_connection_id uuid primary key references public.reporting_integration_connections(id) on delete cascade,
  encrypted_credentials bytea not null,
  updated_at timestamptz not null default now()
);

revoke all on schema reporting_private from public, anon, authenticated;
revoke all on all tables in schema reporting_private from public, anon, authenticated;

create table public.sync_logs (
  id bigint generated by default as identity primary key,
  integration_connection_id uuid not null references public.reporting_integration_connections(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null,
  records_imported bigint not null default 0,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index companies_organization_idx on public.companies (organization_id);
create index services_company_idx on public.services (company_id);
create index campaigns_company_channel_idx on public.campaigns (company_id, channel_id);
create index daily_metrics_company_date_idx on public.daily_marketing_metrics (company_id, date);
create index daily_metrics_campaign_idx on public.daily_marketing_metrics (campaign_id);
create index daily_metrics_channel_idx on public.daily_marketing_metrics (channel_id);
create index daily_metrics_service_idx on public.daily_marketing_metrics (service_id);
create index website_metrics_company_date_idx on public.website_metrics (company_id, date);
create index seo_metrics_company_date_idx on public.seo_metrics (company_id, date);
create index gbp_metrics_company_date_idx on public.gbp_metrics (company_id, date);
create index leads_company_created_idx on public.leads (company_id, created_at desc);
create index leads_campaign_idx on public.leads (campaign_id);
create index leads_channel_idx on public.leads (channel_id);
create index leads_service_idx on public.leads (service_id);
create index leads_stage_idx on public.leads (sales_stage);
create index lead_events_lead_occurred_idx on public.lead_events (lead_id, occurred_at);
create index projects_service_idx on public.projects (service_id);
create index revenue_attribution_company_idx on public.revenue_attribution (company_id, attributed_at);
create index reporting_integrations_company_idx on public.reporting_integration_connections (company_id);

alter table public.organizations enable row level security;
alter table public.companies enable row level security;
alter table public.users enable row level security;
alter table public.company_users enable row level security;
alter table public.services enable row level security;
alter table public.marketing_channels enable row level security;
alter table public.campaigns enable row level security;
alter table public.ad_groups enable row level security;
alter table public.ads enable row level security;
alter table public.creative_metadata enable row level security;
alter table public.daily_marketing_metrics enable row level security;
alter table public.website_metrics enable row level security;
alter table public.seo_metrics enable row level security;
alter table public.gbp_metrics enable row level security;
alter table public.leads enable row level security;
alter table public.lead_events enable row level security;
alter table public.appointments enable row level security;
alter table public.quotes enable row level security;
alter table public.projects enable row level security;
alter table public.revenue_attribution enable row level security;
alter table public.reporting_integration_connections enable row level security;
alter table public.sync_logs enable row level security;

create policy "users can read own profile" on public.users for select to authenticated using (id = (select auth.uid()));
create policy "users can read own company memberships" on public.company_users for select to authenticated using (user_id = (select auth.uid()));

create policy "organization members can read organization" on public.organizations for select to authenticated using (
  id in (select organization_id from public.users where id = (select auth.uid()))
);

create policy "authorized users can read companies" on public.companies for select to authenticated using (
  organization_id in (select organization_id from public.users where id = (select auth.uid()) and role in ('super_admin', 'agency_admin'))
  or id in (select company_id from public.company_users where user_id = (select auth.uid()))
);

create policy "authorized users can read services" on public.services for select to authenticated using (
  company_id in (select id from public.companies)
);
create policy "authorized users can read campaigns" on public.campaigns for select to authenticated using (
  company_id in (select id from public.companies)
);
create policy "authorized users can read ad groups" on public.ad_groups for select to authenticated using (
  campaign_id in (select id from public.campaigns)
);
create policy "authorized users can read ads" on public.ads for select to authenticated using (
  ad_group_id in (select id from public.ad_groups)
);
create policy "authorized users can read creative metadata" on public.creative_metadata for select to authenticated using (
  ad_id in (select id from public.ads)
);
create policy "organization users can read channels" on public.marketing_channels for select to authenticated using (
  organization_id in (select organization_id from public.users where id = (select auth.uid()))
);
create policy "authorized users can read marketing metrics" on public.daily_marketing_metrics for select to authenticated using (company_id in (select id from public.companies));
create policy "authorized users can read website metrics" on public.website_metrics for select to authenticated using (company_id in (select id from public.companies));
create policy "authorized users can read seo metrics" on public.seo_metrics for select to authenticated using (company_id in (select id from public.companies));
create policy "authorized users can read gbp metrics" on public.gbp_metrics for select to authenticated using (company_id in (select id from public.companies));
create policy "authorized users can read leads" on public.leads for select to authenticated using (company_id in (select id from public.companies));
create policy "authorized users can read lead events" on public.lead_events for select to authenticated using (lead_id in (select id from public.leads));
create policy "authorized users can read appointments" on public.appointments for select to authenticated using (lead_id in (select id from public.leads));
create policy "authorized users can read quotes" on public.quotes for select to authenticated using (lead_id in (select id from public.leads));
create policy "authorized users can read projects" on public.projects for select to authenticated using (lead_id in (select id from public.leads));
create policy "authorized users can read attribution" on public.revenue_attribution for select to authenticated using (company_id in (select id from public.companies));
create policy "admins can read reporting integrations" on public.reporting_integration_connections for select to authenticated using (
  company_id in (select id from public.companies)
  and exists (select 1 from public.users where id = (select auth.uid()) and role in ('super_admin', 'agency_admin', 'company_admin'))
);
create policy "admins can read sync logs" on public.sync_logs for select to authenticated using (
  integration_connection_id in (select id from public.reporting_integration_connections)
);

revoke all on public.reporting_integration_connections from anon;
revoke all on public.sync_logs from anon;
grant select on public.organizations, public.companies, public.users, public.company_users, public.services, public.marketing_channels,
  public.campaigns, public.ad_groups, public.ads, public.creative_metadata, public.daily_marketing_metrics, public.website_metrics,
  public.seo_metrics, public.gbp_metrics, public.leads, public.lead_events, public.appointments, public.quotes, public.projects,
  public.revenue_attribution, public.reporting_integration_connections, public.sync_logs to authenticated;
